### ISSUE TITLE
Home feed misses many tweets

### ISSUE THREAD

**Issue by tuckervento** [tuckervento/Tinfoil-Twitter#2]
The news feed seems to be missing entire blocks of tweets, seeming to be related to when the feed is refreshed.  Try clearing the cache on each load of the app, and on each hard refresh? Maybe include caching as a setting.  Look into using webView.clearCache(true) or manually removing the cache db.

**Comment by richq** [comment]
Is this still a problem? Seems to work OK at the moment.

**Comment by tuckervento** [comment]
I don't think so, I recently stopped seeing this behavior.  However, someone recently contacted me saying they *just started* seeing it, so I'm not too sure..
