### ISSUE TITLE
change icon to 't' letter wrapped with tinfoil.

### ISSUE THREAD

**Issue by KOLANICH** [tuckervento/Tinfoil-Twitter#7]

**Comment by tuckervento** [comment]
I have very limited gfx abilities.  If you (or anyone else) wanted to contribute this, I wouldn't have a problem merging it in, but for now I'm happy with the parallel icon to Tinfoil for Facebook.

**Comment by KOLANICH** [comment]
>I'm happy with the parallel icon to Tinfoil for Facebook.
Isn't this a problem that they can be confused with each other?

**Comment by m1ga** [comment]
How about something like this?
![g3586](https://cloud.githubusercontent.com/assets/4334997/7004379/f1aa4a8c-dc6a-11e4-90c0-074ae87239a1.png)

[download svg](http://www.migaweb.de/tinfoil_twitter.svg)

**Comment by KOLANICH** [comment]
Good. :)

**Comment by tuckervento** [comment]
Thanks!  I'll get this into production soon
